version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  datacollector:
    build: 
      context: ./services/DataCollector/DataCollector
    depends_on:
      - redis

  dataprocessor:
    build: 
      context: ./services/DataProcessor/DataProcessor
    depends_on:
      - redis
      - datacollector

  apigateway:
    build: 
      context: ./services/ApiGateway/ApiGateway
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - dataprocessor

  frontend:
    build: 
      context: ./Frontend/social_ui
    ports:
      - "5173:80"
    depends_on:
      - apigateway